### ISSUE TITLE
截图的分辨率低，没有等比例缩放的手段

### ISSUE THREAD

**Issue by wwjCMP** [MarkMindLtd/Roam-Mind#10]
截图的分辨率低，能否提高？
没有保持比例缩放的手段，还是我没找到？

**Comment by MarkMindLtd** [comment]
截图正确了吗？

分辨率的问题在高清屏可能较突出，不过你可以先放大PDF在截图

**Comment by wwjCMP** [comment]
> 截图正确了吗？
> 
> 分辨率的问题在高清屏可能较突出，不过你可以先放大PDF在截图

截图现在用着没什么问题
