### ISSUE TITLE
目录不清

### ISSUE THREAD

**Issue by Jamie-Wan** [MarkMindLtd/Roam-Mind#3]
这个问题在知乎上提过，背景是灰色，目录字体是白色，辨识度不高

**Comment by MarkMindLtd** [comment]
这个目录是指 PDF 目录吗？能否截个图明确一下

**Comment by Jamie-Wan** [comment]
是PDF的目录。
![image](https://user-images.githubusercontent.com/65280479/121192206-481ac000-c89f-11eb-803d-73f14b3a5cad.png)
