### ISSUE TITLE
【bug】截图错位

### ISSUE THREAD

**Issue by wwjCMP** [MarkMindLtd/Roam-Mind#8]
系统版本	window 10.0.18363
软件版本 0.04

![Snipaste_2021-06-09_09-51-50](https://user-images.githubusercontent.com/32979859/121280434-db3c1000-c908-11eb-8783-ae58362b47ee.png)
上图是截图
下图是笔记显示
![Snipaste_2021-06-09_09-52-02](https://user-images.githubusercontent.com/32979859/121280444-e000c400-c908-11eb-95bf-83e67ba13082.png)

**Comment by MarkMindLtd** [comment]
> 系统版本 window 10.0.18363
> 软件版本 0.04
> 
> ![Snipaste_2021-06-09_09-51-50](https://user-images.githubusercontent.com/32979859/121280434-db3c1000-c908-11eb-8783-ae58362b47ee.png)
> 上图是截图
> 下图是笔记显示
> ![Snipaste_2021-06-09_09-52-02](https://user-images.githubusercontent.com/32979859/121280444-e000c400-c908-11eb-95bf-83e67ba13082.png)

画布裁剪的位置出现问题，但是从矩形生成的位置看，坐标并没有计算错误，待检查修复

**Comment by MarkMindLtd** [comment]
您是使用的高分屏吗

**Comment by wwjCMP** [comment]
> 您是使用的高清屏吗

	
产品	 TUO240E 240E
固件程序日期	2017 年 28 周 (非显示器制造日期)
屏幕尺寸	23.8 英寸 (52 厘米 x 31 厘米)
显示比例	宽屏 16 : 9
分辨率	2560 x 1440 (缩放比例:125%) 32 位真彩色

**Comment by MarkMindLtd** [comment]
已确定问题所在，下个版本修复
