### ISSUE TITLE
【bug】0.04版本链接出现错乱

### ISSUE THREAD

**Issue by wwjCMP** [MarkMindLtd/Roam-Mind#9]
更新0.04之后
一、有些文件的链接出现错误，不能链接到正确的pdf文件。
二、新建pdf笔记链接，不显示引用的原文。

**Comment by MarkMindLtd** [comment]
要保持 pdf 文件相对位置不变

之前的版本 标注有可能出现位置错乱

**Comment by MarkMindLtd** [comment]
之后会允许设置 pdf 文件的保存位置

**Comment by MarkMindLtd** [comment]
' 新建pdf笔记链接，不显示引用的原文。'

这个能否截个图？

**Comment by wwjCMP** [comment]
> ' 新建pdf笔记链接，不显示引用的原文。'
> 
> 这个能否截个图？
{"id":"16482d920b6a-1f7f-d08e-283e","type":"highlight","action":"create pdf annotate","selectText":""}
只有位置坐标没有原文
![Uploading Snipaste_2021-06-09_14-49-35.png…]()

**Comment by wwjCMP** [comment]
![Snipaste_2021-06-09_14-49-35](https://user-images.githubusercontent.com/32979859/121306863-f2432800-c931-11eb-8366-ad6e1bc6918b.png)

**Comment by MarkMindLtd** [comment]
> > ' 新建pdf笔记链接，不显示引用的原文。'
> > 这个能否截个图？
> > {"id":"16482d920b6a-1f7f-d08e-283e","type":"highlight","action":"create pdf annotate","selectText":""}
> > 只有位置坐标没有原文
> > ![Snipaste_2021-06-09_14-49-35](https://user-images.githubusercontent.com/32979859/121306894-fbcc9000-c931-11eb-963a-dc8632208869.png)

select text 没有文字，能否把pdf发给我一份，用于测试，邮箱 ckminder@163.com

**Comment by wwjCMP** [comment]
> > > ' 新建pdf笔记链接，不显示引用的原文。'
> > > 这个能否截个图？
> > > {"id":"16482d920b6a-1f7f-d08e-283e","type":"highlight","action":"create pdf annotate","selectText":""}
> > > 只有位置坐标没有原文
> > > ![Snipaste_2021-06-09_14-49-35](https://user-images.githubusercontent.com/32979859/121306894-fbcc9000-c931-11eb-963a-dc8632208869.png)
> 
> select text 没有文字，能否把pdf发给我一份，用于测试，邮箱 [ckminder@163.com](mailto:ckminder@163.com)
不是单个pdf出现的问题，也不是总是出现，有时候可能触发某些bug之后就一直是这样，重启应用都不行。0.03版本没有遇到这些问题。

**Comment by MarkMindLtd** [comment]
> > > > ' 新建pdf笔记链接，不显示引用的原文。'
> > > > 这个能否截个图？
> > > > {"id":"16482d920b6a-1f7f-d08e-283e","type":"highlight","action":"create pdf annotate","selectText":""}
> > > > 只有位置坐标没有原文
> > > > ![Snipaste_2021-06-09_14-49-35](https://user-images.githubusercontent.com/32979859/121306894-fbcc9000-c931-11eb-963a-dc8632208869.png)
> > 
> > 
> > select text 没有文字，能否把pdf发给我一份，用于测试，邮箱 [ckminder@163.com](mailto:ckminder@163.com)
> > 不是单个pdf出现的问题，也不是总是出现，有时候可能触发某些bug之后就一直是这样，重启应用都不行。0.03版本没有遇到这些问题。

发了一个 pre release , 0.0.5 测试版，可以试下
